import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "RownakHayat-WebPortal",
  description: "Generated by rownakhayat@gmai.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body 
     className={`${inter.className} scroll-smooth`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
